---
title: "Untitled"
output: html_document
date: "2024-08-10"
---


working twins vr non-twins 

```{r FC, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)
library(ggsignif)
library(miaViz)
tse <- readRDS("data/twins_tse.rds")
#tse <- subsetByPrevalentFeatures(tse,rank = "Phylum", prevalence = 20/ 100)
#di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
#di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
di<- getDissimilarity(
  x = tse,
 method = "bray",
 assay.type = "counts",
 rarefy = TRUE,
  niter = 100)
di <-reshape2::melt(as.matrix(di)) %>% `colnames<-`(c("X","Y", "value"))


#spling location-wise
tse_list <- splitOn(tse, f= "Geographical_location")
tse_Ahm <- tse_list[[1]]
tse_Pune <- tse_list[[2]]
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Ahm) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
AN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Pune <- tse_list[[2]]
set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
PN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Nashik) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
#rand <- sample(nrow(within_pairs))
pl <- rev(order(within_pairs$pair_2))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[pl])
NS <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
mergedcities <- rbind(AN, PN, NS)
mergedcities$City <- c(rep("Ahmednagar", nrow(AN)),  rep("Pune", nrow(PN)), rep("Nashik", nrow(NS)))
mergedcities$grp <- factor(mergedcities$grp, levels = c("within_pairs", "between_pairs"))
a1 <- ggplot(mergedcities, aes(x=grp,y=value))+
geom_boxplot(outlier.shape = NA)+
geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("within_pairs", "between_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "A") + scale_x_discrete(labels=c("within_pairs" = "Twins", "between_pairs" = "Non-twins")) + theme_bw() + theme(text = element_text(size = 23), axis.text = element_text(size = 23), axis.title = element_text(size = 18))
print(a1)

##At genus level 
tse <- readRDS("data/twins_tse.rds")
#tse <- subsetByPrevalentFeatures(tse,rank = "Phylum", prevalence = 10/ 100)
di<- getDissimilarity(
  x = tse,
 method = "bray",
 assay.type = "counts",
 rarefy = TRUE,
  niter = 100)
di <-reshape2::melt(as.matrix(di)) %>% `colnames<-`(c("X","Y", "value"))

#tse <- subsetByPrevalentFeatures(tse,rank = "Genus", prevalence =20/ 100)
#di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
#di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
#spling location-wise
tse_list <- splitOn(tse, f= "Geographical_location")
tse_Ahm <- tse_list[[1]]
tse_Pune <- tse_list[[2]]
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Ahm) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
AN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Pune <- tse_list[[2]]
set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
PN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Nashik) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
#rand <- sample(nrow(within_pairs))
pl <- rev(order(within_pairs$pair_2))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[pl])
NS <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
mergedcities <- rbind(AN, PN, NS)
mergedcities$City <- c(rep("Ahmednagar", nrow(AN)),  rep("Pune", nrow(PN)), rep("Nashik", nrow(NS)))
mergedcities$grp <- factor(mergedcities$grp, levels = c("within_pairs", "between_pairs"))
a2 <- ggplot(mergedcities, aes(x=grp,y=value))+
geom_boxplot(outlier.shape = NA)+
geom_jitter(aes(colour = City), width= 0.05, size= 2.5) +
#geom_signif(comparisons = list(c("within_pairs", "between_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "A") + scale_x_discrete(labels=c("within_pairs" = "Twins", "between_pairs" = "Non-twins")) + theme_bw() + theme(text = element_text(size = 23), axis.text = element_text(size = 23), axis.title = element_text(size = 18)) + theme_bw(base_size = 20)
print(a2)
library(gridExtra)
gridExtra::grid.arrange(a1, a2, ncol = 2)
```


```{r twinsi1b, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)
library(ggsignif)
library(miaViz)
tse <- readRDS("data/sibdata/sibtwin_tse.rds")
tse <- tse[,!(colnames(tse) %in% c("T6A", "T6B", "T7A", "T7B", "T8A", "T8B", "T9A", "T9B", "T11A", "T11B", "T12A", "T12B", "T13A", "T13B"))]
#tse <- subsetByPrevalentFeatures(tse, rank = "Phylum",prevalence = 10/100)
tse <- agglomerateByPrevalence(tse,rank = "Phylum", prevalence = 10/100)
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
# split tse by twins and sibling
tse_list <- splitOn(tse, f= "Pair")
tse_twin <- tse_list[[1]]
tse_sib <- tse_list[[2]]
set.seed(123)
twin_pairs <- colData(tse_twin) %>% as_tibble() %>% group_by(ID) %>%
summarise(twin_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(twin_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
set.seed(123)
within_pairs <- colData(tse_sib) %>% as_tibble() %>% group_by(ID) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
unrel <- tse[,!(colnames(tse) %in% c("T1A", "T2A", "T3A", "T4A", "T5A", "T10A", "S1", "S3", "S5", "S7", "S9", "S11"))]
#colData(unrel)$Unr <- c("Unr1", "Unr1", "Unr2","Unr2", "Unr3", "Unr3", "Unr4","Unr4", "Unr5", "Unr5", "Unr6","Unr6")
colData(unrel)$Unr <- c("Unr1", "Unr2", "Unr3","Unr4", "Unr5", "Unr6", "Unr1","Unr2", "Unr3", "Unr4", "Unr5","Unr6")
set.seed(123)
unrel_pairs <- colData(unrel) %>% as_tibble() %>% group_by(Unr) %>%
summarise(unrel_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(unrel_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("Unr_1", "Unr_2"))
combined <- rbind(
merge(di, twin_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("twin_pairs",nrow(twin_pairs))),
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, unrel_pairs, by.x=c("X","Y"), by.y=c("Unr_1", "Unr_2")) %>%
mutate(grp=rep("unrel_pairs",nrow(within_pairs))))

combined$grp <- factor(combined$grp, levels = c("unrel_pairs", "within_pairs", "twin_pairs"))
r1 <- ggplot(combined, aes(x = grp, y = value)) +
 geom_boxplot(outlier.shape = NA)+ geom_jitter(width= 0.05, size= 1.7)+
#geom_jitter(aes(colour = grp), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("twin_pairs", "within_pairs"), c("twin_pairs", "unrel_pairs"), c("unrel_pairs","within_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "") + scale_x_discrete(labels=c("twin_pairs" = "Twins", "within_pairs" = "Siblings", "unrel_pairs" = "Unrelated")) + theme_bw(base_size = 20)
print(r1)


## at genus level
tse <- readRDS("data/sibdata/sibtwin_tse.rds")
tse <- tse[,!(colnames(tse) %in% c("T6A", "T6B", "T7A", "T7B", "T8A", "T8B", "T9A", "T9B", "T11A", "T11B", "T12A", "T12B", "T13A", "T13B"))]
tse <- subsetByPrevalentFeatures(tse, rank = "Genus", prevalence = 20/100)
di <- as.matrix(vegdist(t(assay(tse, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
# split tse by twins and sibling
tse_list <- splitOn(tse, f= "Pair")
tse_twin <- tse_list[[1]]
tse_sib <- tse_list[[2]]
set.seed(123)
twin_pairs <- colData(tse_twin) %>% as_tibble() %>% group_by(ID) %>%
summarise(twin_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(twin_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
set.seed(123)
within_pairs <- colData(tse_sib) %>% as_tibble() %>% group_by(ID) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
unrel <- tse[,!(colnames(tse) %in% c("T1A", "T2A", "T3A", "T4A", "T5A", "T10A", "S1", "S3", "S5", "S7", "S9", "S11"))]
#colData(unrel)$Unr <- c("Unr1", "Unr1", "Unr2","Unr2", "Unr3", "Unr3", "Unr4","Unr4", "Unr5", "Unr5", "Unr6","Unr6")
colData(unrel)$Unr <- c("Unr1", "Unr2", "Unr3","Unr4", "Unr5", "Unr6", "Unr1","Unr2", "Unr3", "Unr4", "Unr5","Unr6")
set.seed(123)
unrel_pairs <- colData(unrel) %>% as_tibble() %>% group_by(Unr) %>%
summarise(unrel_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(unrel_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("Unr_1", "Unr_2"))
combined <- rbind(
merge(di, twin_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("twin_pairs",nrow(twin_pairs))),
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, unrel_pairs, by.x=c("X","Y"), by.y=c("Unr_1", "Unr_2")) %>%
mutate(grp=rep("unrel_pairs",nrow(within_pairs))))


#Reorder ggplot boxes 
combined$grp <- factor(combined$grp, levels = c("unrel_pairs", "within_pairs", "twin_pairs"))
r <- ggplot(combined, aes(x = grp, y = value)) +
 geom_boxplot(outlier.shape = NA)+ geom_jitter(width= 0.05, size= 1.7)+
#geom_jitter(aes(colour = grp), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("twin_pairs", "within_pairs"), c("twin_pairs", "unrel_pairs"), c("unrel_pairs","within_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "") + scale_x_discrete(labels=c("twin_pairs" = "Twins", "within_pairs" = "Siblings", "unrel_pairs" = "Unrelated")) + theme_bw(base_size = 20)
print(r)
```


##working##
#  Comparative analysis between Twins, siblings and unrelated pairs at phylum level (rarefraction)

```{r rarecomp, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)
library(ggsignif)
library(miaViz)

tse <- readRDS("data/sibdata/sibtwin_tse.rds")

tse <- tse[,!(colnames(tse) %in% c("T6A", "T6B", "T7A", "T7B", "T8A", "T8B", "T9A", "T9B", "T11A", "T11B", "T12A", "T12B", "T13A", "T13B"))]
#tse <- agglomerateByPrevalence(tse,rank = "Phylum", prevalence = 10/100)
#tse <- subsetByPrevalentFeatures(tse, rank = "Phylum", prevalence = 10/100)
#altExp(tse, "phyla_prevalent") <- agglomerateByPrevalence(tse,rank = "Phylum", prevalence = 10/100)
#altExp(tse, "phylum") <- agglomerateByPrevalence(tse,rank = "Phylum", prevalence = 10/100
#altExp(tse, "phyla_prevalent") <- agglomerateByPrevalence(altExp(tse, "phyla_prevalent"),rank = "Phylum", prevalence = 10/100)

di<- getDissimilarity(
  x = tse,
 method = "bray",
 assay.type = "counts",
 rarefy = TRUE,
  niter = 100)
di <-reshape2::melt(as.matrix(di)) %>% `colnames<-`(c("X","Y", "value"))

#di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray"))
#di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

# split tse by twins and sibling
tse_list <- splitOn(tse, f= "Pair")
tse_twin <- tse_list[[1]]
tse_sib <- tse_list[[2]]
set.seed(123)
twin_pairs <- colData(tse_twin) %>% as_tibble() %>% group_by(ID) %>%
summarise(twin_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(twin_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
set.seed(123)
within_pairs <- colData(tse_sib) %>% as_tibble() %>% group_by(ID) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
unrel <- tse_sub[,!(colnames(tse_sub) %in% c("T1A", "T2A", "T3A", "T4A", "T5A", "T10A", "S1", "S3", "S5", "S7", "S9", "S11"))]
colData(unrel)$Unr <- c("Unr1", "Unr2", "Unr3","Unr4", "Unr5", "Unr6", "Unr1","Unr2", "Unr3", "Unr4", "Unr5","Unr6")
set.seed(123)
unrel_pairs <- colData(unrel) %>% as_tibble() %>% group_by(Unr) %>%
summarise(unrel_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(unrel_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("Unr_1", "Unr_2"))
combined <- rbind(
merge(di, twin_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("twin_pairs",nrow(twin_pairs))),
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, unrel_pairs, by.x=c("X","Y"), by.y=c("Unr_1", "Unr_2")) %>%
mutate(grp=rep("unrel_pairs",nrow(within_pairs))))

combined$grp <- factor(combined$grp, levels = c("unrel_pairs", "within_pairs", "twin_pairs"))
s1 <- ggplot(combined, aes(x = grp, y = value)) +
 geom_boxplot(outlier.shape = NA, lwd=0.8)+ geom_jitter(width= 0.05, size= 1.7)+
#geom_jitter(aes(colour = grp), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("twin_pairs", "within_pairs"), c("twin_pairs", "unrel_pairs"), c("unrel_pairs","within_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "") + scale_x_discrete(labels=c("unrel_pairs" = "Unrelated", "within_pairs" = "Siblings", "twin_pairs" = "Twins")) + theme_bw(base_size = 20)
print(s1)

## at genus level
tse <- readRDS("data/sibdata/sibtwin_tse.rds")
tse <- tse[,!(colnames(tse) %in% c("T6A", "T6B", "T7A", "T7B", "T8A", "T8B", "T9A", "T9B", "T11A", "T11B", "T12A", "T12B", "T13A", "T13B"))]
#tse <- subsetByPrevalentFeatures(tse, rank = "Genus", prevalence = 10/100)
tse <- agglomerateByPrevalence(tse,rank = "Genus", prevalence = 10/100) 
di<- getDissimilarity(
  x = tse,
  method = "bray",
  assay.type = "counts",
  rarefy = TRUE,
  niter = 10)
di <-reshape2::melt(as.matrix(di)) %>% `colnames<-`(c("X","Y", "value"))
# split tse for twins and siblings
tse_list <- splitOn(tse, f= "Pair")
tse_twin <- tse_list[[1]]
tse_sib <- tse_list[[2]]
set.seed(123)
twin_pairs <- colData(tse_twin) %>% as_tibble() %>% group_by(ID) %>%
summarise(twin_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(twin_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
set.seed(123)
within_pairs <- colData(tse_sib) %>% as_tibble() %>% group_by(ID) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
unrel <- tse_sub[,!(colnames(tse_sub) %in% c("T1A", "T2A", "T3A", "T4A", "T5A", "T10A", "S1", "S3", "S5", "S7", "S9", "S11"))]
#colData(unrel)$Unr <- c("Unr1", "Unr1", "Unr2","Unr2", "Unr3", "Unr3", "Unr4","Unr4", "Unr5", "Unr5", "Unr6","Unr6")
colData(unrel)$Unr <- c("Unr1", "Unr2", "Unr3","Unr4", "Unr5", "Unr6", "Unr1","Unr2", "Unr3", "Unr4", "Unr5","Unr6")
set.seed(123)
unrel_pairs <- colData(unrel) %>% as_tibble() %>% group_by(Unr) %>%
summarise(unrel_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(unrel_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("Unr_1", "Unr_2"))
combined <- rbind(
merge(di, twin_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("twin_pairs",nrow(twin_pairs))),
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, unrel_pairs, by.x=c("X","Y"), by.y=c("Unr_1", "Unr_2")) %>%
mutate(grp=rep("unrel_pairs",nrow(within_pairs))))

#Reorder ggplot boxes 
combined$grp <- factor(combined$grp, levels = c("unrel_pairs", "within_pairs", "twin_pairs"))
s <- ggplot(combined, aes(x = grp, y = value)) +
 geom_boxplot(outlier.shape = NA, lwd=0.8)+ geom_jitter(width= 0.05, size= 1.7)+
#geom_jitter(aes(colour = grp), width= 0.05, size= 1.7) +
#geom_signif(comparisons = list(c("twin_pairs", "within_pairs"), c("twin_pairs", "unrel_pairs"), c("unrel_pairs","within_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "B") + scale_x_discrete(labels=c("twin_pairs" = "Twins", "within_pairs" = "Siblings", "unrel_pairs" = "Unrelated")) + theme_bw(base_size = 20)
print(s)
gridExtra::grid.arrange(s1, s, ncol = 2)
```


# Comparative analysis between Twins and Non-twin (rarefraction) 

```{r twins, message=FALSE, echo=FALSE, warning=FALSE}
library(mia)
library(ggplot2)
library(patchwork)
library(ggsignif)
library(ggpubr)
library(scater)
library(tidyverse)
library(vegan)
library(dplyr)
library(magrittr)


# Load data
tse <- readRDS("data/twins_tse.rds")
tse_sub <- subsetByPrevalentFeatures(tse_sub,rank = "Phylum", prevalence = 20/ 100)
di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
#spling location-wise
tse_list <- splitOn(tse_sub, f= "Geographical_location")
tse_Ahm <- tse_list[[1]]
tse_Pune <- tse_list[[2]]
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Ahm) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
AN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Pune <- tse_list[[2]]
set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
PN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Nashik) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
#rand <- sample(nrow(within_pairs))
pl <- rev(order(within_pairs$pair_2))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[pl])
NS <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
mergedcities <- rbind(AN, PN, NS)
mergedcities$City <- c(rep("Ahmednagar", nrow(AN)),  rep("Pune", nrow(PN)), rep("Nashik", nrow(NS)))
mergedcities$grp <- factor(mergedcities$grp, levels = c("within_pairs", "between_pairs"))
a1 <- ggplot(mergedcities, aes(x=grp,y=value))+
geom_boxplot(outlier.shape = NA, lwd=0.8)+
geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("within_pairs", "between_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "A") + scale_x_discrete(labels=c("within_pairs" = "Twins", "between_pairs" = "Non-twins")) + theme_bw(base_size = 20)
print(a1)


################### Genus level#############
tse <- readRDS("data/twins_tse.rds")
#tse <- agglomerateByPrevalence(tse,rank = "Genus", prevalence = 10/100)
#di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray"))
#di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
 
di<- getDissimilarity(
  x = tse,
  method = "bray",
  assay.type = "counts",
  rarefy = TRUE,
  niter = 100)
di <-reshape2::melt(as.matrix(di)) %>% `colnames<-`(c("X","Y", "value"))

#spling location-wise
tse_list <- splitOn(tse, f= "Geographical_location")
tse_Ahm <- tse_list[[1]]
tse_Pune <- tse_list[[2]]
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Ahm) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
AN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Pune <- tse_list[[2]]
set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
PN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Nashik) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
#rand <- sample(nrow(within_pairs))
pl <- rev(order(within_pairs$pair_2))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[pl])
NS <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
mergedcities <- rbind(AN, PN, NS)
mergedcities$City <- c(rep("Ahmednagar", nrow(AN)),  rep("Pune", nrow(PN)), rep("Nashik", nrow(NS)))
mergedcities$grp <- factor(mergedcities$grp, levels = c("within_pairs", "between_pairs")) #re-order
a2 <- ggplot(mergedcities, aes(x=grp,y=value))+
geom_boxplot(outlier.shape = NA, lwd=0.8)+
geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("within_pairs", "between_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "B") + scale_x_discrete(labels=c("within_pairs" = "Twins", "between_pairs" = "Non-twins")) + theme_bw(base_size = 20)
print(a2)
library(gridExtra)
gridExtra::grid.arrange(a1, a2, ncol = 2)
```

# Comparative analysis between Twins and Non-twin (niter) 

```{r twins, message=FALSE, echo=FALSE, warning=FALSE}
library(mia)
library(ggplot2)
library(patchwork)
library(ggsignif)
library(ggpubr)
library(scater)
library(tidyverse)
library(vegan)
library(dplyr)
library(magrittr)


# Load data
tse <- readRDS("data/twins_tse.rds")

tse <- addAlpha(tse, assay.type = "counts", index = "shannon", name = "shannon", sample = min(colSums(assay(tse, "counts")), na.rm = TRUE), niter=10)

tse_sub <- subsetByPrevalentFeatures(tse_sub,rank = "Phylum", prevalence = 20/ 100)
di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray", niter = 10), niter= 10)
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
#spling location-wise
tse_list <- splitOn(tse_sub, f= "Geographical_location")
tse_Ahm <- tse_list[[1]]
tse_Pune <- tse_list[[2]]
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Ahm) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
AN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Pune <- tse_list[[2]]
set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
PN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Nashik) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
#rand <- sample(nrow(within_pairs))
pl <- rev(order(within_pairs$pair_2))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[pl])
NS <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
mergedcities <- rbind(AN, PN, NS)
mergedcities$City <- c(rep("Ahmednagar", nrow(AN)),  rep("Pune", nrow(PN)), rep("Nashik", nrow(NS)))
mergedcities$grp <- factor(mergedcities$grp, levels = c("within_pairs", "between_pairs"))
a1 <- ggplot(mergedcities, aes(x=grp,y=value))+
geom_boxplot(outlier.shape = NA, lwd=0.8)+
geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("within_pairs", "between_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "A") + scale_x_discrete(labels=c("within_pairs" = "Twins", "between_pairs" = "Non-twins")) + theme_bw(base_size = 20)
print(a1)


################### Genus level#############
tse <- readRDS("data/twins_tse.rds")
tse_sub <- subsetByPrevalentFeatures(tse_sub,rank = "Genus", prevalence = 20/ 100)
di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray"), niter=10)
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

#spling location-wise
tse_list <- splitOn(tse, f= "Geographical_location")
tse_Ahm <- tse_list[[1]]
tse_Pune <- tse_list[[2]]
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Ahm) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
AN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Pune <- tse_list[[2]]
set.seed(123)
within_pairs <- colData(tse_Pune) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
rand <- sample(nrow(within_pairs))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[rand])
PN <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
tse_Nashik <- tse_list[[3]]
set.seed(123)
within_pairs <- colData(tse_Nashik) %>% as_tibble() %>% group_by(Pair) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("pair_1", "pair_2"))
#rand <- sample(nrow(within_pairs))
pl <- rev(order(within_pairs$pair_2))
between_pairs <- data.frame(pair_1=within_pairs$pair_1, pair_2=within_pairs$pair_2[pl])
NS <- rbind(
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, between_pairs, by.x=c("X","Y"), by.y=c("pair_1", "pair_2")) %>%
mutate(grp=rep("between_pairs",nrow(between_pairs))))
mergedcities <- rbind(AN, PN, NS)
mergedcities$City <- c(rep("Ahmednagar", nrow(AN)),  rep("Pune", nrow(PN)), rep("Nashik", nrow(NS)))
mergedcities$grp <- factor(mergedcities$grp, levels = c("within_pairs", "between_pairs")) #re-order
a2 <- ggplot(mergedcities, aes(x=grp,y=value))+
geom_boxplot(outlier.shape = NA, lwd=0.8)+
geom_jitter(aes(colour = City), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("within_pairs", "between_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "B") + scale_x_discrete(labels=c("within_pairs" = "Twins", "between_pairs" = "Non-twins")) + theme_bw(base_size = 20)
print(a2)
library(gridExtra)
gridExtra::grid.arrange(a1, a2, ncol = 2)
```
#  Feb 2025 Comparative analysis between Twins, siblings and unrelated pairs at phylum level (rarefraction)

```{r rarecomp, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(mia)
library(vegan)
library(scater)
library(dplyr)
library(tidyverse)
library(magrittr)
library(ggsignif)
library(miaViz)

tse <- readRDS("data/sibdata/sibtwin_tse.rds")

# Calculate the list of sequencing depths across samples
sequencing_depths <- colSums(assay(tse))
# Calculate variation between highest and lowest sequencing depth
depth_variation <- max(sequencing_depths)/min(sequencing_depths)
depth_variation

# Let us see what happens when we operate with ntop highest variance features
ntop <- 5

# Calculate the standard deviations for each row
row_sds <- rowSds(assay(tse, "counts"))

# Get the indices of the top 5 rows with the highest standard deviations
top_indices <- order(row_sds, decreasing = TRUE)[1:ntop]

# Subset the tse object based on the top indices
tse_sub <- tse[top_indices, ]


tse_sub <- tse_sub[,!(colnames(tse_sub) %in% c("T6A", "T6B", "T7A", "T7B", "T8A", "T8B", "T9A", "T9B", "T11A", "T11B", "T12A", "T12B", "T13A", "T13B"))]
tse_sub <- subsetByPrevalentFeatures(tse_sub,
rank = "Phylum",
prevalence = 10/100)



tse_sub <- runMDS(
  tse_sub,
  FUN = getDissimilarity,
  method = "bray",
  assay.type = "counts",
  name = "MDS_bray"
  )


# Define custom transformation function..
counts <- function (x) {
  vegan::decostand(x, method="counts", pseudocount=1)
}

# Run transformation after rarefactions before calculating the beta diversity..
tse_sub <- runMDS(tse_sub,
  assay.type = "counts",
  ntop = nrow(tse_sub),
  FUN = getDissimilarity,
  method = "bray",
  niter = 10, # Number of iterations
  sample = min(colSums(assay(tse_sub, "log"))), # Rarefaction depth
  transf = counts, # Applied transformation
  replace = TRUE,
  name = "MDS_rarefied"
  )




di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))

# split tse by twins and sibling
tse_list <- splitOn(tse_sub, f= "Pair")
tse_twin <- tse_list[[1]]
tse_sib <- tse_list[[2]]
set.seed(123)
twin_pairs <- colData(tse_twin) %>% as_tibble() %>% group_by(ID) %>%
summarise(twin_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(twin_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
set.seed(123)
within_pairs <- colData(tse_sib) %>% as_tibble() %>% group_by(ID) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
unrel <- tse_sub[,!(colnames(tse_sub) %in% c("T1A", "T2A", "T3A", "T4A", "T5A", "T10A", "S1", "S3", "S5", "S7", "S9", "S11"))]
colData(unrel)$Unr <- c("Unr1", "Unr2", "Unr3","Unr4", "Unr5", "Unr6", "Unr1","Unr2", "Unr3", "Unr4", "Unr5","Unr6")
set.seed(123)
unrel_pairs <- colData(unrel) %>% as_tibble() %>% group_by(Unr) %>%
summarise(unrel_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(unrel_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("Unr_1", "Unr_2"))
combined <- rbind(
merge(di, twin_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("twin_pairs",nrow(twin_pairs))),
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, unrel_pairs, by.x=c("X","Y"), by.y=c("Unr_1", "Unr_2")) %>%
mutate(grp=rep("unrel_pairs",nrow(within_pairs))))

combined$grp <- factor(combined$grp, levels = c("unrel_pairs", "within_pairs", "twin_pairs"))
s1 <- ggplot(combined, aes(x = grp, y = value)) +
 geom_boxplot(outlier.shape = NA, lwd=0.8)+ geom_jitter(width= 0.05, size= 1.7)+
#geom_jitter(aes(colour = grp), width= 0.05, size= 1.7) +
geom_signif(comparisons = list(c("twin_pairs", "within_pairs"), c("twin_pairs", "unrel_pairs"), c("unrel_pairs","within_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "A") + scale_x_discrete(labels=c("twin_pairs" = "Twins", "within_pairs" = "Siblings", "unrel_pairs" = "Unrelated")) + theme_bw(base_size = 20)
print(s1)

## at genus level
tse <- readRDS("data/sibdata/sibtwin_tse.rds")
# Calculate the list of sequencing depths across samples
sequencing_depths <- colSums(assay(tse))
# Calculate variation between highest and lowest sequencing depth
depth_variation <- max(sequencing_depths)/min(sequencing_depths)
depth_variation

# Let us see what happens when we operate with ntop highest variance features
ntop <- 5

# Calculate the standard deviations for each row
row_sds <- rowSds(assay(tse, "counts"))

# Get the indices of the top 5 rows with the highest standard deviations
top_indices <- order(row_sds, decreasing = TRUE)[1:ntop]

# Subset the tse object based on the top indices
tse_sub <- tse[top_indices, ]

tse_sub <- tse[,!(colnames(tse_sub) %in% c("T6A", "T6B", "T7A", "T7B", "T8A", "T8B", "T9A", "T9B", "T11A", "T11B", "T12A", "T12B", "T13A", "T13B"))]
tse_sub <- subsetByPrevalentFeatures(tse_sub, rank = "Genus", prevalence = 10/100)
di <- as.matrix(vegdist(t(assay(tse_sub, "counts")), method="bray"))
di <- reshape2::melt(di) %>% `colnames<-`(c("X","Y", "value"))
# split tse for twins and siblings
tse_list <- splitOn(tse_sub, f= "Pair")
tse_twin <- tse_list[[1]]
tse_sib <- tse_list[[2]]
set.seed(123)
twin_pairs <- colData(tse_twin) %>% as_tibble() %>% group_by(ID) %>%
summarise(twin_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(twin_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
set.seed(123)
within_pairs <- colData(tse_sib) %>% as_tibble() %>% group_by(ID) %>%
summarise(within_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(within_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("ID_1", "ID_2"))
unrel <- tse_sub[,!(colnames(tse_sub) %in% c("T1A", "T2A", "T3A", "T4A", "T5A", "T10A", "S1", "S3", "S5", "S7", "S9", "S11"))]
#colData(unrel)$Unr <- c("Unr1", "Unr1", "Unr2","Unr2", "Unr3", "Unr3", "Unr4","Unr4", "Unr5", "Unr5", "Unr6","Unr6")
colData(unrel)$Unr <- c("Unr1", "Unr2", "Unr3","Unr4", "Unr5", "Unr6", "Unr1","Unr2", "Unr3", "Unr4", "Unr5","Unr6")
set.seed(123)
unrel_pairs <- colData(unrel) %>% as_tibble() %>% group_by(Unr) %>%
summarise(unrel_pairs=combn(Samples, 2, simplify = FALSE)) %>%
dplyr::select(unrel_pairs) %>% .[[1]] %>% do.call(rbind, .) %>%
as.data.frame() %>% `colnames<-`(c("Unr_1", "Unr_2"))
combined <- rbind(
merge(di, twin_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("twin_pairs",nrow(twin_pairs))),
merge(di, within_pairs, by.x=c("X","Y"), by.y=c("ID_1", "ID_2")) %>%
mutate(grp=rep("within_pairs",nrow(within_pairs))),
merge(di, unrel_pairs, by.x=c("X","Y"), by.y=c("Unr_1", "Unr_2")) %>%
mutate(grp=rep("unrel_pairs",nrow(within_pairs))))

#Reorder ggplot boxes 
combined$grp <- factor(combined$grp, levels = c("unrel_pairs", "within_pairs", "twin_pairs"))
s <- ggplot(combined, aes(x = grp, y = value)) +
 geom_boxplot(outlier.shape = NA, lwd=0.8)+ geom_jitter(width= 0.05, size= 1.7)+
#geom_jitter(aes(colour = grp), width= 0.05, size= 1.7) +
#geom_signif(comparisons = list(c("twin_pairs", "within_pairs"), c("twin_pairs", "unrel_pairs"), c("unrel_pairs","within_pairs")), map_signif_level = FALSE) +
theme(text = element_text(size = 10)) + labs(x = "", y= "Bray-Curtis index", title = "B") + scale_x_discrete(labels=c("twin_pairs" = "Twins", "within_pairs" = "Siblings", "unrel_pairs" = "Unrelated")) + theme_bw(base_size = 20)
print(s)
gridExtra::grid.arrange(s1, s, ncol = 2)
```
